### ISSUE TITLE
a little help please

### ISSUE THREAD

**Issue by jaygrovr** [RubenDijk/ender3-home-assistant#1]
when you say put the files in the correct location, can you be a bit more specific?

thanks
jason

**Comment by RubenDijk** [comment]
When using split config:
Copy the content from the folders to the correct folders

configuration.yaml (no split config)

octoprint: (configuration.yaml)
camera: (configuration.yaml)
place switch under the switch: (configuration.yaml)
place the automation under automation.yaml
Place everything from the scripts folder under script.yaml 

hope this helps you

**Comment by jaygrovr** [comment]
so the 10 script files you have packaged, those all need to be combined and put into one file, or can they be put seperately.  I dont have a folder named scripts, just a single file.
ThanksJason
    On Tuesday, April 14, 2020, 12:22:16 AM PDT, Ruben Dijk <notifications@github.com> wrote:  
 
 


When using split config:
Copy the content from the folders to the correct folders

configuration.yaml (no split config)

octoprint: (configuration.yaml)
camera: (configuration.yaml)
place switch under the switch: (configuration.yaml)
place the automation under automation.yaml
Place everything from the scripts folder under script.yaml

hope this helps you

**Comment by RubenDijk** [comment]
pls see new readme. 
https://github.com/RubenDijk/ender3-home-assistant/blob/master/readme_non_split.md

**Comment by jaygrovr** [comment]
where does the rest configuration go?
jason
    On Tuesday, April 14, 2020, 11:52:01 AM PDT, Ruben Dijk <notifications@github.com> wrote:  
 
 


pls see new readme.
https://github.com/RubenDijk/ender3-home-assistant/blob/master/readme_non_split.md

**Comment by RubenDijk** [comment]
rest_command: !include ender3_rest_commands.yaml
ther i put my rest commands

**Comment by RubenDijk** [comment]
Any luck setting it up?

**Comment by jaygrovr** [comment]
Ruben, yes I was able to get it setup.  I had one issue though, if my switched outlet which powers my printer is already on, it seems home assistant doesnt know that.  I have to check why that is happening.  It was a powerstrip thing that was flashed with tasmota.  Im sure there is a setting I missed to make that work better.
ThanksJason
    On Friday, April 17, 2020, 12:40:44 AM PDT, Ruben Dijk <notifications@github.com> wrote:  
 
 


Any luck setting it up?

**Comment by RubenDijk** [comment]
something in the state(the return message) message from tasmota
https://stevessmarthomeguide.com/setting-up-the-sonoff-tasmota-mqtt-switch/
